# details of APIs
apis:
  - name: News
    description: This is an API which users can query by keywords topics publications
    tags: [news,info]
    context: news
    version: 1
    resources:
     - method: GET
       path: menu

  - name: Places
    description: Users can find popular places like food shops banks etc using this API
    tags: [places]
    context: places
    version: 1
    resources:
      - method: GET
        path: menu

  - name: Payment
    description: 
    tags: []
    context: payment
    version: 1
    resources:
      - method: GET
        path: menu
      - method: POST
        path: order
      - method: DELETE
        path: order

  - name: Map
    description: This is an API providing location data traffic info real-time updates etc
    tags: [maps]
    context: map
    version: 1
    resources:
      - method: GET
        path: menu
      - method: DELETE
        path: order

  - name: Weather
    description: Users can query about whether info in a particular location country or city
    tags: [weather]
    context: weather
    version: 1
    resources:
      - method: GET
        path: menu
      - method: DELETE
        path: order

  - name: Cricket
    description: This is a cricket API providing live scores teams player details etc
    tags: [cricket]
    context: cricket
    version: 1
    resources:
      - method: GET
        path: menu
      - method: DELETE
        path: order
